export const light = {
  name: 'light',
  colors: {
    background: '#FFFFFF',
    secondaryColor: '#E7E7E7',
    thirdColor: '#71717A',
    cardColor: '#F4F4F5',
    primaryTextColor: '#27272A',
    secondaryTextColor: '#3A3A3D',
    secondaryTextState: '#71717A',
    formBackgroudColor: '#F4F4F5',
    footerListTitleColor: '#27272A',
    footerListColor: '#71717A',
    depoimentBackground: '#F4F4F5',
    borderColor: '#D4D4D8',
    themeHoverColor: '#E4E4E4',
    logoColor: '#181818',
    detailColor: 'rgba(39, 39, 42, 0.2)',
    detailTitleColor: '#0345A8',
    detailTitleColorHover: '#7CAAEF',
    headerBorderBottomColor: '#EAEAEA',
    navigationMenuBackground: '#FFFFFF',
    navigationMenuBorder: '#EAEAEA',
    linkFooterHover: '#161617',
    hoverNavigationMenuItem: '#FAFAFA',
    hoverColor: '#FAFAFA',
    headerHover: '#000000',
    buttonBackgroudColor: '#7CAAEF',
    buttonBackgroudColorHover: '#5586CD'
  }
}
